In [1]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [ ]:
! pip install joblib

In [2]:
np.random.randn(3)

array([ 0.77701823,  0.57798473, -0.10292864])

In [3]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int=None):
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta
        self.epochs =epochs
        
    def fit(self,X,y):
        self.X = X
        self.y =y
        X_with_bias = np.c_[self.X, -np.ones(len(self.X),1)]  
        print(f"X with bias:\n{X_with_bias}")
        

In [4]:
obj = Perceptron(eta = 0.01,epochs =10)

In [5]:
obj.weights

array([-4.95918257e-05,  1.17003998e-04, -3.21255114e-05])

In [6]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
X = np.ones((4,2))

In [8]:
y = X = np.ones((4,1))

In [9]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [10]:
obj.fit(X,y)

TypeError: Cannot interpret '1' as a data type